name: NPM Publish

on:
  push:
    tags:
      - "v*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout codes
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Publish
      run: |
        cp ./README_zh-CN.md ./package/hexo-theme-async
        cp ./README.md ./package/hexo-theme-async
        node ./script/publish
        cd ./package/hexo-theme-async
        npm publish
      env:
        RELEASE_VERSION: ${{ github.ref}}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}